apiVersion: v2
name: trivy-operator
description: Trivy Operator managed by App of Apps
version: 1.0.0
type: application
dependencies:
  - name: trivy-operator
    version: 0.32.0
    repository: https://aquasecurity.github.io/helm-charts/
