environment: prod

repo:
  url: git@github.com:filipegalo/cluster-bootstrap.git
  targetRevision: main

argocd:
  enabled: true

externalSecrets:
  enabled: true

vault:
  enabled: false

argocdRepoSecret:
  enabled: true

kubePrometheusStack:
  enabled: true

reloader:
  enabled: true

trivyOperator:
  enabled: true
