vault:
  injector:
    enabled: false
  ui:
    enabled: true

vaultSeed:
  enabled: true
  secretName: repo-ssh-key
  secretNamespace: argocd
  secretKey: sshPrivateKey
  vaultSecretPath: argocd/repo-ssh-key

vaultConfig:
  enabled: true
  role: external-secrets
  serviceAccount: external-secrets
  serviceAccountNamespace: external-secrets
  policyName: external-secrets
  policyPath: "secret/*"
