vault:
  server:
    standalone:
      enabled: false
    dataStorage:
      enabled: true
      size: 10Gi
    ha:
      enabled: true
      replicas: 1
      raft:
        enabled: true

vaultAutoUnseal:
  enabled: true

