{{- if .Values.vaultAutoUnseal.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-auto-unseal
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-auto-unseal
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault-auto-unseal
subjects:
  - kind: ServiceAccount
    name: vault
    namespace: {{ .Release.Namespace }}
{{- end }}
