apiVersion: v2
name: reloader
description: Stakater Reloader managed by App of Apps
version: 1.0.0
type: application
dependencies:
  - name: reloader
    version: 2.2.8
    repository: https://stakater.github.io/stakater-charts
